version: "3.7"

services:
  mongo:
    image: mongo:4.4-focal@sha256:0032f4a04bf96ca9c69665a553198148bdd8ec8caf556eb6281a464d3cb32470
    ports:
      - target: 27017
        published: 27017

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    build:
      context: .
      dockerfile: docker/Dockerfile-uwsgi
    entrypoint:
      - uwsgi
      - --ini
      - /etc/stupidchess/uwsgi.ini:local
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /etc/stupidchess/config
    volumes:
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess
      - type: bind
        source: ./uwsgi.ini
        target: /etc/stupidchess/uwsgi.ini
        read_only: true
      - type: bind
        source: ./config
        target: /etc/stupidchess/config
        read_only: true

  nginx:
    image: jnorwood/stupidchess-nginx:2023.9.3
    volumes:
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

  socat:
    image: jnorwood/stupidchess-socat:current
    build:
      context: docker
      dockerfile: Dockerfile-socat
    ports:
      - published: 23180
        target: 23080
    volumes:
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

volumes:
  frontend-public-volume:
  stupidchess-nginx-runtime:
  stupidchess-sockets:
