version: "3.7"

volumes:
  frontend-public-volume:
  socket-volume:

services:
  mongo:
    image: mongo:6.0-jammy@sha256:aefae4865d1a803f4ffc543bc9b26694025c4faa3517b6dc45c4065e89b6cc7c
    ports:
      - target: 27017
        published: 27017

  nginx:
    image: jnorwood/stupidchess-nginx:23.0621.0
    volumes:
      - type: volume
        source: socket-volume
        target: /run/stupidchess
    ports:
      - target: 23080
        published: 80

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    build: .
    entrypoint:
      - uwsgi
      - --ini
      - /etc/stupidchess/uwsgi.ini:local
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /etc/stupidchess/config
    volumes:
      - type: volume
        source: socket-volume
        target: /run/stupidchess
      - type: bind
        source: ./uwsgi.ini
        target: /etc/stupidchess/uwsgi.ini
        read_only: true
      - type: bind
        source: ./config
        target: /etc/stupidchess/config
        read_only: true
