version: "3.7"

services:
  mongo:
    image: mongo:6.0-jammy@sha256:aefae4865d1a803f4ffc543bc9b26694025c4faa3517b6dc45c4065e89b6cc7c
    ports:
      - target: 27017
        published: 27017

  uwsgi:
    image: jnorwood/stupidchess-uwsgi:current
    build:
      context: .
      dockerfile: docker/Dockerfile-uwsgi
    entrypoint:
      - uwsgi
      - --ini
      - /etc/stupidchess/uwsgi.ini:local
    environment:
      JCONFIGURE_ACTIVE_PROFILES: LCL
      JCONFIGURE_CONFIG_DIRECTORIES: /etc/stupidchess/config
    volumes:
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess
      - type: bind
        source: ./uwsgi.ini
        target: /etc/stupidchess/uwsgi.ini
        read_only: true
      - type: bind
        source: ./config
        target: /etc/stupidchess/config
        read_only: true

  nginx:
    image: jnorwood/stupidchess-nginx:2023.8.0
    volumes:
      - type: volume
        source: stupidchess-sockets
        target: /run/stupidchess
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

  socat:
    image: jnorwood/stupidchess-socat:current
    build:
      context: docker
      dockerfile: Dockerfile-socat
    ports:
      - published: 80
        target: 23180
    volumes:
      - type: volume
        source: stupidchess-nginx-runtime
        target: /run/stupidchess-nginx

volumes:
  frontend-public-volume:
  stupidchess-nginx-runtime:
  stupidchess-sockets:
