#!/usr/local/bin/python


class Offsets:
    FORWARD_OFFSET = -10
    BACKWARD_OFFSET = 10
    LEFT_OFFSET = -1
    RIGHT_OFFSET = 1

    LEFT_FORWARD_OFFSET = -11
    RIGHT_FORWARD_OFFSET = -9
    RIGHT_BACKWARD_OFFSET = 11
    LEFT_BACKWARD_OFFSET = 9
