#!/usr/local/bin/python


class Offsets:
    FORWARD_ONE_OFFSET = 10
    FORWARD_TWO_OFFSET = FORWARD_ONE_OFFSET * 2

    LEFT_ONE_OFFSET = -1
    RIGHT_ONE_OFFSET = 1

    DIAGONAL_LEFT_OFFSET = 9
    DIAGONAL_RIGHT_OFFSET = 11

    MIDDLE_BOARD_FORWARD_OFFSET = 1
    MIDDLE_BOARD_DIAGONAL_OFFSET = -9
