FROM python
MAINTAINER John Norwood

RUN pip install uwsgi
COPY server /var/lib/johnmalcolmnorwood/stupidchess
WORKDIR /var/lib/johnmalcolmnorwood/stupidchess/
RUN python setup.py install

COPY etc/uwsgi.ini /etc/uwsgi/uwsgi.ini

EXPOSE 8000
ENTRYPOINT ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini:local"]
