FROM jnorwood/rpi-python:3.5.2
MAINTAINER John Norwood <norwood.john.m@gmail.com>

COPY server /var/lib/johnmalcolmnorwood/stupidchess/server
WORKDIR /var/lib/johnmalcolmnorwood/stupidchess/server
RUN python setup.py install
VOLUME /usr/local/lib/python3.5/site-packages
