FROM hypriot/rpi-node:7.0.0
MAINTAINER John Norwood <norwood.john.m@gmail.com>

RUN npm install -g webpack

COPY web/package.json /var/lib/johnmalcolmnorwood/stupidchess/
WORKDIR /var/lib/johnmalcolmnorwood/stupidchess
RUN npm install

COPY web/.babelrc /var/lib/johnmalcolmnorwood/stupidchess/
COPY web/.eslintrc /var/lib/johnmalcolmnorwood/stupidchess/
COPY web/webpack.config.js /var/lib/johnmalcolmnorwood/stupidchess/

VOLUME /var/lib/johnmalcolmnorwood/stupidchess/dist

ENTRYPOINT ["webpack", "-p", "--progress"]
