FROM node:8.3-alpine
LABEL maintainer=norwood.john.m@gmail.com

WORKDIR /var/lib/johnmalcolmnorwood/stupidchess
COPY web/package.json .
RUN npm install

COPY web/.babelrc .
COPY web/.eslintrc .
COPY web/webpack.config.js .

ENTRYPOINT ["node_modules/webpack/bin/webpack.js", "-p", "--progress"]
