FROM python:3.6-alpine
MAINTAINER John Norwood <norwood.john.m@gmail.com>

COPY server/requirements.txt .
RUN apk add --no-cache \
        build-base \
        linux-headers \
        libffi-dev \
    && pip install -r requirements.txt

ARG APP_DIR=/var/lib/johnmalcolmnorwood/stupidchess/server
WORKDIR ${APP_DIR}

COPY server/packages .

RUN cd auth && pip install .
RUN cd stupidchess && pip install .

COPY server/config ./config
COPY etc/uwsgi/uwsgi.ini /etc/uwsgi/uwsgi.ini

ENTRYPOINT ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini"]
