FROM python:3.6-alpine
MAINTAINER John Norwood <norwood.john.m@gmail.com>

RUN apk add --no-cache \
        build-base \
        linux-headers \
        libffi-dev \
    && pip install uwsgi

ARG APP_DIR=/var/lib/johnmalcolmnorwood/stupidchess/server

COPY etc/uwsgi/uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY server/packages ${APP_DIR}
COPY config ${APP_DIR}/config

WORKDIR ${APP_DIR}

RUN cd auth && python setup.py install
RUN cd stupidchess && python setup.py install

VOLUME /tmp/sockets
ENTRYPOINT ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini"]
