FROM python:3.6-alpine
MAINTAINER John Norwood <norwood.john.m@gmail.com>

RUN apk add --no-cache \
        build-base \
        linux-headers \
        libffi-dev \
    && pip install uwsgi

ARG APP_DIR=/var/lib/johnmalcolmnorwood/stupidchess/server
WORKDIR ${APP_DIR}

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY server/packages .
COPY config ./config
COPY etc/uwsgi/uwsgi.ini /etc/uwsgi/uwsgi.ini

RUN cd auth && python setup.py install
RUN cd stupidchess && python setup.py install

VOLUME /tmp/sockets
ENTRYPOINT ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini"]
