FROM jnorwood/rpi-python:3.5.2
MAINTAINER John Norwood <norwood.john.m@gmail.com>

RUN apt-get update \
    && apt-get install libffi-dev \
    && rm -rf /var/lib/apt/lists/* \
    && pip install uwsgi

ARG APP_DIR=/var/lib/johnmalcolmnorwood/stupidchess/server

COPY etc/uwsgi/uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY server/packages ${APP_DIR}

WORKDIR ${APP_DIR}

RUN cd auth && python setup.py install
RUN cd stupidchess && python setup.py install

VOLUME /tmp
ENTRYPOINT ["uwsgi", "--ini", "/etc/uwsgi/uwsgi.ini"]
